twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '_layout/form/modal_form_theme.html.twig'
    globals:
        accounts: '@App\Twig\AccountsGlobal'

when@test:
    twig:
        strict_variables: true
