<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The table that lets a calendar client ask what changed.
 *
 * WHY IT EXISTS
 * ─────────────
 * `App\Jmap\Calendar\CalendarState` is the string `'fixed'`, and its docblock
 * explains at length that this is a confession rather than a design: mail has a
 * complete change log and calendars have none, so `canCalculateChanges` is
 * false, there is no `CalendarEvent/changes`, and every client re-runs its query
 * instead. It ends by naming the table that would end that. This is it.
 *
 * CalDAV needs the same rows for a different question. RFC 6578's
 * sync-collection REPORT is "what changed in this collection since token N",
 * which is this table filtered by calendar_id, and a deletion has to come back
 * as a `404` for an href the client still holds — so a deleted event must leave
 * something behind that still names it.
 *
 * NO FOREIGN KEYS, WHICH IS THE POINT
 * ───────────────────────────────────
 * user_id, calendar_id and event_id are plain integers. event_id must be,
 * because the row outlives the event: a tombstone constrained to reference the
 * thing it records the death of could not be written. `jmap_change_log` stores
 * account_id the same way and gives the other half of the reason — these rows
 * are written during flush, where holding entity references is the documented
 * footgun.
 *
 * The cost is that rows for a deleted calendar are not cleaned up by the
 * database. That is deliberate and cheap: once a collection is gone no reader
 * asks about it, and `CalendarChangeLogRepository::pruneOlderThan()` exists for
 * whoever decides to reclaim the space.
 *
 * EVENT_UID IS A COPY, ON PURPOSE
 * ───────────────────────────────
 * Denormalised from the event because it is the only surviving record of it. A
 * CalDAV client names a resource by a URL built from the UID; resolving it by
 * join at read time works for every row except the ones that matter.
 *
 * TWO INDEXES, ONE PER READER
 * ───────────────────────────
 * CalDAV always names one collection, so calendar_id leads. JMAP's
 * CalendarEvent/changes spans every calendar a user has, so user_id leads there.
 * Neither serves the other: a scan by user over an index led by calendar would
 * read every collection's history to answer about one user's, and the reverse
 * skips the collection filter entirely. Both take their ordering from the
 * sequence that follows the leading column.
 *
 * PRE-1.0, SO NO BACKFILL
 * ───────────────────────
 * The log starts empty and every existing event is unrecorded. That is correct
 * rather than tolerated: a client's first sync is a full read regardless — it
 * has no token yet — and inventing history for events nobody has asked about
 * would write a sequence no reader could have been at.
 */
final class Version20260903130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add calendar_change_log: the state token JMAP and CalDAV both count from';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE calendar_change_log (
                sequence INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                calendar_id INT NOT NULL,
                event_id INT NOT NULL,
                event_uid VARCHAR(255) NOT NULL,
                change_kind VARCHAR(16) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (sequence)
            )
            SQL);

        $this->addSql('CREATE INDEX idx_calendar_change_log_calendar_sequence ON calendar_change_log (calendar_id, sequence)');
        $this->addSql('CREATE INDEX idx_calendar_change_log_user_sequence ON calendar_change_log (user_id, sequence)');
    }

    public function down(Schema $schema): void
    {
        // Nothing an operator typed lives here, and a client that loses the log
        // resyncs from scratch — which is what it did before the table existed.
        $this->addSql('DROP TABLE calendar_change_log');
    }
}
