<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The table behind "report this mail" — a user telling the extractors what
 * they missed.
 *
 * Every link is nullable and every one of them is ON DELETE SET NULL, which is
 * unusual enough in this schema to be worth stating here as well as on the
 * entity: the row's value is the SNAPSHOT it carries, not the mail it points
 * at. A report that cascades away with an archived message is a report that
 * deletes itself exactly when it has become the only surviving copy of the
 * shape somebody wanted parsed.
 *
 * body_text, subject and the address columns are TEXT rather than VARCHAR(n)
 * for the reason the mail tables already use TEXT: a subject line has no real
 * bound, and a truncation that happens in the database is a truncation nobody
 * chose. The one bound that IS chosen lives in PHP as
 * InsightReport::MAX_BODY_CHARS, where it can be explained.
 */
final class Version20260820120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add insight_report: mails users flag as missing an insight';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE insight_report (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                reported_by_id INT DEFAULT NULL,
                account_id INT DEFAULT NULL,
                message_id INT DEFAULT NULL,
                from_address TEXT DEFAULT NULL,
                from_name TEXT DEFAULT NULL,
                subject TEXT DEFAULT NULL,
                received_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                body_text TEXT DEFAULT NULL,
                note TEXT DEFAULT NULL,
                handled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_insight_report_created_at ON insight_report (created_at)');
        $this->addSql('CREATE INDEX idx_insight_report_handled_at ON insight_report (handled_at)');
        $this->addSql('CREATE INDEX IDX_INSIGHT_REPORT_REPORTED_BY ON insight_report (reported_by_id)');
        $this->addSql('CREATE INDEX IDX_INSIGHT_REPORT_ACCOUNT ON insight_report (account_id)');
        $this->addSql('CREATE INDEX IDX_INSIGHT_REPORT_MESSAGE ON insight_report (message_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE insight_report
                ADD CONSTRAINT FK_INSIGHT_REPORT_REPORTED_BY
                FOREIGN KEY (reported_by_id) REFERENCES "user" (id)
                ON DELETE SET NULL NOT DEFERRABLE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE insight_report
                ADD CONSTRAINT FK_INSIGHT_REPORT_ACCOUNT
                FOREIGN KEY (account_id) REFERENCES account (id)
                ON DELETE SET NULL NOT DEFERRABLE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE insight_report
                ADD CONSTRAINT FK_INSIGHT_REPORT_MESSAGE
                FOREIGN KEY (message_id) REFERENCES message (id)
                ON DELETE SET NULL NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE insight_report');
    }
}
