<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A second push transport, and somewhere to keep the credentials it needs.
 *
 * fcm_config is one row for the whole installation, and `singleton` plus its
 * unique index is what says so. The column is a constant 1 that nothing reads:
 * it exists because "there is exactly one Firebase project here" is otherwise a
 * rule living in a repository method, and a rule living in a repository method
 * is one INSERT away from two rows and a config that depends on planner order.
 *
 * Only service_account_json is encrypted, through EncryptedStringType, so that
 * column is TEXT and the ciphertext is the application's business. Everything
 * beside it is clear on purpose: project_id and client_email appear in every
 * request the sender makes, and application_id, api_key and sender_id are the
 * values an Android client is HANDED in its session so it can initialise
 * Firebase at runtime — they ship inside every Firebase APK and encrypting a
 * value the server publishes would suggest a guarantee that does not exist.
 * android_package records which client of a multi-app google-services.json was
 * taken, because otherwise "the wrong variant won" is invisible.
 *
 * The three columns on jmap_push_subscription are the row learning what it is.
 * `transport` is NOT NULL with a default of 'webpush' rather than nullable:
 * every subscription that exists at this point is a Web Push one, the default
 * backfills them in the same statement, and a null there would make the
 * dispatcher pick a sender by accident for rows nobody has touched since.
 * fcm_token is TEXT and encrypted for the same reason the mail passwords are —
 * it is the entire address of one person's phone, and a backup outlives the
 * install that made it.
 *
 * **url loses its NOT NULL, and that is the one non-additive line here.** An
 * FCM subscription has no endpoint; the alternative was storing '' and
 * discovering it at send time. Dropping a NOT NULL never fails and never
 * rewrites the table, and no existing row changes — but it is a widening, so
 * down() cannot simply put it back: any FCM subscription created in the
 * meantime has a null url and would refuse the constraint. down() therefore
 * deletes the FCM rows first, which is the honest reading of "undo this
 * feature" and is called out here because migrations run automatically on boot
 * and a reader of the changelog is entitled to know what a rollback costs.
 */
final class Version20260806171500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Give a push subscription a transport and let Firebase credentials live in the database';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE fcm_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, singleton INT DEFAULT 1 NOT NULL, is_enabled BOOLEAN NOT NULL, service_account_json TEXT DEFAULT NULL, project_id VARCHAR(255) DEFAULT NULL, client_email VARCHAR(255) DEFAULT NULL, application_id VARCHAR(255) DEFAULT NULL, api_key VARCHAR(255) DEFAULT NULL, sender_id VARCHAR(64) DEFAULT NULL, android_package VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fcm_config_singleton ON fcm_config (singleton)');

        $this->addSql("ALTER TABLE jmap_push_subscription ADD transport VARCHAR(16) DEFAULT 'webpush' NOT NULL");
        $this->addSql('ALTER TABLE jmap_push_subscription ADD fcm_token TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE jmap_push_subscription ALTER url DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // Before the constraint goes back on, or the ALTER fails on exactly the
        // rows this feature created.
        $this->addSql("DELETE FROM jmap_push_subscription WHERE transport = 'fcm'");

        $this->addSql('ALTER TABLE jmap_push_subscription ALTER url SET NOT NULL');
        $this->addSql('ALTER TABLE jmap_push_subscription DROP fcm_token');
        $this->addSql('ALTER TABLE jmap_push_subscription DROP transport');

        $this->addSql('DROP TABLE fcm_config');
    }
}
