<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260626091910 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) DEFAULT NULL, imap_host VARCHAR(255) NOT NULL, imap_port INT NOT NULL, imap_encryption VARCHAR(20) NOT NULL, username VARCHAR(255) NOT NULL, password TEXT DEFAULT NULL, smtp_host VARCHAR(255) DEFAULT NULL, smtp_port INT DEFAULT NULL, smtp_encryption VARCHAR(20) DEFAULT NULL, auth_type VARCHAR(20) NOT NULL, oauth_provider VARCHAR(255) DEFAULT NULL, oauth_access_token TEXT DEFAULT NULL, oauth_refresh_token TEXT DEFAULT NULL, oauth_token_expiry TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D3656A4C69D3FB ON account (usr_id)');
        $this->addSql('CREATE TABLE mailbox (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, full_path VARCHAR(500) NOT NULL, delimiter VARCHAR(5) DEFAULT NULL, special_use VARCHAR(50) DEFAULT NULL, uid_validity INT DEFAULT NULL, last_seen_uid INT DEFAULT NULL, total_messages INT DEFAULT NULL, unread_messages INT DEFAULT NULL, is_sync_enabled BOOLEAN NOT NULL, synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A69FE20B9B6B5FBA ON mailbox (account_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, imap_uid INT NOT NULL, message_id TEXT DEFAULT NULL, subject TEXT DEFAULT NULL, from_address VARCHAR(320) DEFAULT NULL, from_name TEXT DEFAULT NULL, to_addresses JSON DEFAULT NULL, cc_addresses JSON DEFAULT NULL, bcc_addresses JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, starred_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, in_reply_to VARCHAR(320) DEFAULT NULL, "references" TEXT DEFAULT NULL, size INT DEFAULT NULL, has_attachments BOOLEAN NOT NULL, synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, flags JSON DEFAULT NULL, body_text TEXT DEFAULT NULL, body_html TEXT DEFAULT NULL, mailbox_id INT NOT NULL, thread_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F66EC35CC ON message (mailbox_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FE2904019 ON message (thread_id)');
        $this->addSql('CREATE TABLE message_part (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content_type VARCHAR(255) NOT NULL, filename VARCHAR(255) DEFAULT NULL, content_id VARCHAR(255) DEFAULT NULL, disposition VARCHAR(255) NOT NULL, size INT DEFAULT NULL, storage_path TEXT DEFAULT NULL, is_inline BOOLEAN NOT NULL, message_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E09AEB1F537A1329 ON message_part (message_id)');
        $this->addSql('CREATE TABLE message_thread (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject TEXT DEFAULT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, message_count INT NOT NULL, unread_count INT NOT NULL, tab VARCHAR(255) DEFAULT NULL, starred_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_607D18C9B6B5FBA ON message_thread (account_id)');
        $this->addSql('CREATE TABLE message_thread_mailbox (message_thread_id INT NOT NULL, mailbox_id INT NOT NULL, PRIMARY KEY (message_thread_id, mailbox_id))');
        $this->addSql('CREATE INDEX IDX_49B25E0A8829462F ON message_thread_mailbox (message_thread_id)');
        $this->addSql('CREATE INDEX IDX_49B25E0A66EC35CC ON message_thread_mailbox (mailbox_id)');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4C69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mailbox ADD CONSTRAINT FK_A69FE20B9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F66EC35CC FOREIGN KEY (mailbox_id) REFERENCES mailbox (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE2904019 FOREIGN KEY (thread_id) REFERENCES message_thread (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_part ADD CONSTRAINT FK_E09AEB1F537A1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_thread ADD CONSTRAINT FK_607D18C9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_thread_mailbox ADD CONSTRAINT FK_49B25E0A8829462F FOREIGN KEY (message_thread_id) REFERENCES message_thread (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_thread_mailbox ADD CONSTRAINT FK_49B25E0A66EC35CC FOREIGN KEY (mailbox_id) REFERENCES mailbox (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A4C69D3FB');
        $this->addSql('ALTER TABLE mailbox DROP CONSTRAINT FK_A69FE20B9B6B5FBA');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F66EC35CC');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FE2904019');
        $this->addSql('ALTER TABLE message_part DROP CONSTRAINT FK_E09AEB1F537A1329');
        $this->addSql('ALTER TABLE message_thread DROP CONSTRAINT FK_607D18C9B6B5FBA');
        $this->addSql('ALTER TABLE message_thread_mailbox DROP CONSTRAINT FK_49B25E0A8829462F');
        $this->addSql('ALTER TABLE message_thread_mailbox DROP CONSTRAINT FK_49B25E0A66EC35CC');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE mailbox');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE message_part');
        $this->addSql('DROP TABLE message_thread');
        $this->addSql('DROP TABLE message_thread_mailbox');
    }
}
