<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260727205101 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add jmap_push_subscription — outbound Web Push endpoints per device.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE jmap_push_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, device_client_id VARCHAR(255) NOT NULL, url TEXT NOT NULL, p256dh VARCHAR(255) DEFAULT NULL, auth VARCHAR(255) DEFAULT NULL, types JSON DEFAULT NULL, expires TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, verification_code VARCHAR(64) DEFAULT NULL, verified BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, failure_count INT NOT NULL, usr_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_push_user ON jmap_push_subscription (usr_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_push_device ON jmap_push_subscription (usr_id, device_client_id)');
        $this->addSql('ALTER TABLE jmap_push_subscription ADD CONSTRAINT FK_79282A2DC69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE jmap_push_subscription DROP CONSTRAINT FK_79282A2DC69D3FB');
        $this->addSql('DROP TABLE jmap_push_subscription');
    }
}
