<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260721092957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE log_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, channel VARCHAR(64) NOT NULL, level INT NOT NULL, level_name VARCHAR(32) NOT NULL, message TEXT NOT NULL, context JSON DEFAULT NULL, source VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_log_entry_created_at ON log_entry (created_at)');
        $this->addSql('CREATE INDEX idx_log_entry_level ON log_entry (level)');
        $this->addSql('CREATE INDEX idx_log_entry_channel ON log_entry (channel)');
        $this->addSql('CREATE TABLE process_heartbeat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(64) NOT NULL, beat_key VARCHAR(128) NOT NULL, pid INT DEFAULT NULL, last_beat_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, meta JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_heartbeat_type_key ON process_heartbeat (type, beat_key)');
        $this->addSql('ALTER TABLE account ADD gmail_last_push_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE account ADD oauth_last_refresh_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE account ADD oauth_last_refresh_error TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE log_entry');
        $this->addSql('DROP TABLE process_heartbeat');
        $this->addSql('ALTER TABLE account DROP gmail_last_push_at');
        $this->addSql('ALTER TABLE account DROP oauth_last_refresh_at');
        $this->addSql('ALTER TABLE account DROP oauth_last_refresh_error');
    }
}
