<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719110720 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE label (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, role VARCHAR(50) DEFAULT NULL, gmail_label_id VARCHAR(255) DEFAULT NULL, color VARCHAR(30) DEFAULT NULL, is_visible BOOLEAN DEFAULT true NOT NULL, sort_order INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA750E8727ACA70 ON label (parent_id)');
        $this->addSql('CREATE INDEX idx_label_account ON label (account_id)');
        $this->addSql('CREATE INDEX idx_label_gmail_label_id ON label (gmail_label_id)');
        $this->addSql('CREATE TABLE message_label (message_id INT NOT NULL, label_id INT NOT NULL, PRIMARY KEY (message_id, label_id))');
        $this->addSql('CREATE INDEX IDX_F101AF03537A1329 ON message_label (message_id)');
        $this->addSql('CREATE INDEX IDX_F101AF0333B92F39 ON message_label (label_id)');
        $this->addSql('CREATE TABLE thread_label (message_thread_id INT NOT NULL, label_id INT NOT NULL, PRIMARY KEY (message_thread_id, label_id))');
        $this->addSql('CREATE INDEX IDX_4234FD38829462F ON thread_label (message_thread_id)');
        $this->addSql('CREATE INDEX IDX_4234FD333B92F39 ON thread_label (label_id)');
        $this->addSql('ALTER TABLE label ADD CONSTRAINT FK_EA750E89B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE label ADD CONSTRAINT FK_EA750E8727ACA70 FOREIGN KEY (parent_id) REFERENCES label (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_label ADD CONSTRAINT FK_F101AF03537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_label ADD CONSTRAINT FK_F101AF0333B92F39 FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE thread_label ADD CONSTRAINT FK_4234FD38829462F FOREIGN KEY (message_thread_id) REFERENCES message_thread (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thread_label ADD CONSTRAINT FK_4234FD333B92F39 FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mailbox ADD label_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE mailbox ADD CONSTRAINT FK_A69FE20B33B92F39 FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_A69FE20B33B92F39 ON mailbox (label_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE label DROP CONSTRAINT FK_EA750E89B6B5FBA');
        $this->addSql('ALTER TABLE label DROP CONSTRAINT FK_EA750E8727ACA70');
        $this->addSql('ALTER TABLE message_label DROP CONSTRAINT FK_F101AF03537A1329');
        $this->addSql('ALTER TABLE message_label DROP CONSTRAINT FK_F101AF0333B92F39');
        $this->addSql('ALTER TABLE thread_label DROP CONSTRAINT FK_4234FD38829462F');
        $this->addSql('ALTER TABLE thread_label DROP CONSTRAINT FK_4234FD333B92F39');
        $this->addSql('DROP TABLE label');
        $this->addSql('DROP TABLE message_label');
        $this->addSql('DROP TABLE thread_label');
        $this->addSql('ALTER TABLE mailbox DROP CONSTRAINT FK_A69FE20B33B92F39');
        $this->addSql('DROP INDEX IDX_A69FE20B33B92F39');
        $this->addSql('ALTER TABLE mailbox DROP label_id');
    }
}
