<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The radar's table: mail_insight, one row per fact read out of somebody's
 * mail — a parcel, a flight, a ticket, a pull request.
 *
 * Additive; nothing existing is touched and no backfill runs here. Existing
 * mailboxes get their rows from `app:backfill insights`, which the harvester
 * makes idempotent by the unique (account_id, dedupe_key) below — that
 * constraint is also what turns a carrier's five status mails into one row
 * under concurrent ingestion.
 *
 * thread_id and message_id are SET NULL on purpose: the insight can outlive
 * the mail that announced it (a deleted shipping confirmation does not
 * un-ship the parcel); it merely loses its link. account_id CASCADEs — no
 * account, no radar.
 */
final class Version20260817165438 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create mail_insight — the extracted parcels, flights, tickets and code review behind the radar';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mail_insight (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(32) NOT NULL, title VARCHAR(255) NOT NULL, payload JSON NOT NULL, happens_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, extractor VARCHAR(32) NOT NULL, dedupe_key VARCHAR(160) NOT NULL, dismissed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, thread_id INT DEFAULT NULL, message_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_248992B49B6B5FBA ON mail_insight (account_id)');
        $this->addSql('CREATE INDEX IDX_248992B4E2904019 ON mail_insight (thread_id)');
        $this->addSql('CREATE INDEX IDX_248992B4537A1329 ON mail_insight (message_id)');
        $this->addSql('CREATE INDEX idx_mail_insight_happens_at ON mail_insight (happens_at)');
        $this->addSql('CREATE INDEX idx_mail_insight_created_at ON mail_insight (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_mail_insight_account_dedupe ON mail_insight (account_id, dedupe_key)');
        $this->addSql('ALTER TABLE mail_insight ADD CONSTRAINT FK_248992B49B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mail_insight ADD CONSTRAINT FK_248992B4E2904019 FOREIGN KEY (thread_id) REFERENCES message_thread (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mail_insight ADD CONSTRAINT FK_248992B4537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE mail_insight DROP CONSTRAINT FK_248992B49B6B5FBA');
        $this->addSql('ALTER TABLE mail_insight DROP CONSTRAINT FK_248992B4E2904019');
        $this->addSql('ALTER TABLE mail_insight DROP CONSTRAINT FK_248992B4537A1329');
        $this->addSql('DROP TABLE mail_insight');
    }
}
