<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The senders a reader has agreed to load remote images from.
 *
 * Remote images are blocked for everybody by default now, which is the whole
 * point — a tracking pixel that fires on open tells the sender the message was
 * read, from which IP, in which client, at what time. The block is only livable
 * if there is a way to say "not this one", and this table is that way.
 *
 * The unique constraint is load-bearing rather than tidy. Trusting a sender is
 * a button in a message, and the same message can be open in two tabs; without
 * it, a double click is either two rows or a lost update, and the repository
 * would have to SELECT before every INSERT and still lose the race.
 *
 * ON DELETE CASCADE on the user: this is a preference, and a deleted account's
 * preferences have nothing left to be about.
 */
final class Version20260811173000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Per-user allowlist of senders whose remote images may load';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE trusted_image_sender (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, usr_id INT NOT NULL, address VARCHAR(320) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D291D89BC69D3FB ON trusted_image_sender (usr_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_trusted_image_sender ON trusted_image_sender (usr_id, address)');
        $this->addSql('ALTER TABLE trusted_image_sender ADD CONSTRAINT FK_D291D89BC69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE trusted_image_sender');
    }
}
