<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Somewhere for a push attempt to leave a trace.
 *
 * Push was the one thing this server did that left nothing behind: a
 * notification that never arrived looked exactly like one the user did not
 * notice, and answering "did my phone get that?" meant reading container logs
 * for a line that is only written when something goes wrong. push_delivery is
 * one row per attempt per device, written by both transports, including the
 * verification handshake.
 *
 * **There is deliberately no column for the payload.** payload_type holds the
 * `@type` — StateChange or PushVerification — and nothing else of the object is
 * stored. A StateChange carries the account ids and state tokens that moved, so
 * keeping it would turn this table into a retained, admin-readable index of
 * when each user's mail arrives. The type answers the only question the log is
 * for; the rest would be a copy of everyone's mail activity.
 *
 * **No foreign key to jmap_push_subscription, and that is the point.** The most
 * valuable row here is the one written as a subscription is destroyed — an FCM
 * UNREGISTERED, a Web Push 410 — and a cascading reference would delete the
 * evidence in the same statement that creates the need for it. The device is
 * named by the client-chosen device_client_id instead, which also survives the
 * re-registration that replaces the row, so one device reads as one history.
 * usr_id does cascade: a deleted user should not leave a per-device timeline
 * behind.
 *
 * Additive in full — one new table, nothing altered — so there is no backfill
 * and an install that never sends a push simply has an empty table. Retention
 * is `app:monitoring:prune`, which now sweeps this alongside the log entries.
 */
final class Version20260806163217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Record every push attempt, without recording what was pushed';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE push_delivery (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                usr_id INT NOT NULL,
                device_client_id VARCHAR(255) NOT NULL,
                transport VARCHAR(16) NOT NULL,
                payload_type VARCHAR(64) DEFAULT NULL,
                outcome VARCHAR(24) NOT NULL,
                detail VARCHAR(128) DEFAULT NULL,
                latency_ms INT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        $this->addSql('CREATE INDEX idx_push_delivery_created_at ON push_delivery (created_at)');
        $this->addSql('CREATE INDEX idx_push_delivery_device ON push_delivery (usr_id, device_client_id, created_at)');

        $this->addSql(<<<'SQL'
            ALTER TABLE push_delivery
                ADD CONSTRAINT fk_push_delivery_usr
                FOREIGN KEY (usr_id) REFERENCES "user" (id)
                ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE push_delivery');
    }
}
