<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Two-factor authentication.
 *
 * Nothing to backfill: no existing user has 2FA, which is exactly what the
 * null secret and empty code list mean.
 */
final class Version20260731033024 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add TOTP secret, recovery codes and the trusted_device table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE trusted_device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, firewall VARCHAR(64) NOT NULL, label VARCHAR(120) NOT NULL, user_agent TEXT DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_trusted_device_user ON trusted_device (usr_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_trusted_device_hash ON trusted_device (token_hash)');
        $this->addSql('ALTER TABLE trusted_device ADD CONSTRAINT FK_F37E8F7BC69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD totp_secret TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD totp_confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD backup_codes JSONB DEFAULT \'[]\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE trusted_device DROP CONSTRAINT FK_F37E8F7BC69D3FB');
        $this->addSql('DROP TABLE trusted_device');
        $this->addSql('ALTER TABLE "user" DROP totp_secret');
        $this->addSql('ALTER TABLE "user" DROP totp_confirmed_at');
        $this->addSql('ALTER TABLE "user" DROP backup_codes');
    }
}
