<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Somewhere to keep work that is too big for a request.
 *
 * Selecting a whole view and marking it read did all of it inline: every thread
 * hydrated, every message loaded, an ownership check apiece, then the write. On
 * a mailbox with five thousand unread that is `Maximum execution time of 30
 * seconds exceeded` — a broken page, and no way to tell how much of it had
 * happened.
 *
 * State on a row rather than in a message, for the reason MailRule's run state
 * gives: a job over a large mailbox takes minutes and the person who started it
 * closes the tab. The row is what answers "is it done?" afterwards, on any
 * device; Mercure only nudges a page that is still open.
 *
 * Rows are pruned by the maintenance sweep, so this does not grow for ever.
 */
final class Version20260826010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add background_job: bulk mail actions that run outside the request.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE background_job (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                usr_id INT NOT NULL,
                kind VARCHAR(32) NOT NULL,
                state VARCHAR(16) DEFAULT 'queued' NOT NULL,
                total INT DEFAULT 0 NOT NULL,
                processed INT DEFAULT 0 NOT NULL,
                view JSON NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                failure_reason TEXT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX IDX_D01ABE64C69D3FB ON background_job (usr_id)');

        // The indicator's own query: this user's jobs, by state. Without it
        // every page render on a large installation scans the table.
        $this->addSql('CREATE INDEX idx_background_job_owner_state ON background_job (usr_id, state)');

        $this->addSql(<<<'SQL'
            ALTER TABLE background_job
                ADD CONSTRAINT FK_D01ABE64C69D3FB
                FOREIGN KEY (usr_id) REFERENCES "user" (id)
                ON DELETE CASCADE
                NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE background_job');
    }
}
