<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260729095407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add mail_rule — user-scoped Gmail-style filters. Conditions are stored as the same JMAP filter AST the Email/query compiler consumes, so one rule runs both in memory on incoming mail and as SQL over existing mail.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mail_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, conditions JSONB DEFAULT \'{}\' NOT NULL, actions JSONB DEFAULT \'[]\' NOT NULL, is_enabled BOOLEAN DEFAULT true NOT NULL, sort_order INT DEFAULT 0 NOT NULL, stop_processing BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_id INT NOT NULL, account_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EBA33FA59B6B5FBA ON mail_rule (account_id)');
        $this->addSql('CREATE INDEX idx_mail_rule_usr ON mail_rule (usr_id)');
        $this->addSql('ALTER TABLE mail_rule ADD CONSTRAINT FK_EBA33FA5C69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mail_rule ADD CONSTRAINT FK_EBA33FA59B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE mail_rule DROP CONSTRAINT FK_EBA33FA5C69D3FB');
        $this->addSql('ALTER TABLE mail_rule DROP CONSTRAINT FK_EBA33FA59B6B5FBA');
        $this->addSql('DROP TABLE mail_rule');
    }
}
