<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260725083833 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE email_alias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address VARCHAR(320) NOT NULL, display_name VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, source VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7C212A1B9B6B5FBA ON email_alias (account_id)');
        $this->addSql('CREATE INDEX idx_email_alias_address ON email_alias (address)');
        $this->addSql('CREATE UNIQUE INDEX uniq_email_alias_account_address ON email_alias (account_id, address)');
        $this->addSql('ALTER TABLE email_alias ADD CONSTRAINT FK_7C212A1B9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE email_alias DROP CONSTRAINT FK_7C212A1B9B6B5FBA');
        $this->addSql('DROP TABLE email_alias');
    }
}
