<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * One row per model call, and nothing about what was in it.
 *
 * WHAT IS NOT HERE IS THE POINT
 * ─────────────────────────────
 * No prompt, no completion, no message id, no subject, no address. A table
 * that recorded what was asked would be a second copy of the mailbox kept
 * outside every retention rule the mail itself obeys — on an installation
 * whose entire argument for running a local model is that nothing leaves the
 * building. `error_kind` is a category from a closed set for the same reason:
 * an HTTP client's exception message routinely carries the request body back
 * with it, and the request body is somebody's correspondence.
 *
 * WHY THE DURATIONS ARE BIGINT
 * ────────────────────────────
 * Ollama answers in NANOSECONDS. A two-minute generation is 1.2e11, which is
 * about thirty times what a 32-bit column holds — so the first slow answer on
 * a large model would be the row that overflowed. Nothing reads these back
 * into a PHP object: the aggregates cast in SQL and the repository casts at
 * its boundary, which keeps Doctrine's habit of hydrating bigint as a *string*
 * on PostgreSQL out of the question entirely.
 *
 * WHY EVERY GENERATION FIELD IS NULLABLE
 * ──────────────────────────────────────
 * An embedding has no generation phase. /api/embed returns no eval_count and
 * no eval_duration, and the older /api/embeddings returns no timings at all.
 * Null is the truth about those calls. Zero would be a lie sitting in the
 * middle of every percentile, dragging p50 toward nothing.
 *
 * TWO INDEXES, BOTH LEADING WITH THE GROUPING COLUMN
 * ──────────────────────────────────────────────────
 * Every question this table exists to answer is "one bucket, over a window":
 * GROUP BY feature or GROUP BY model, WHERE created_at >= x. Leading with
 * created_at instead would turn both of them into a scan of the whole window.
 */
final class Version20260827000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add ai_call_metric: counts and durations per model call, and nothing else.';
    }

    public function up(Schema $schema): void
    {
        // `GENERATED BY DEFAULT AS IDENTITY` rather than SERIAL: that is what
        // this project's identity_generation_preferences produce, and
        // background_job is the precedent. ai_settings' SERIAL is the outlier.
        $this->addSql(<<<'SQL'
            CREATE TABLE ai_call_metric (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                feature VARCHAR(32) NOT NULL,
                model VARCHAR(128) NOT NULL,
                prompt_tokens INT DEFAULT NULL,
                prompt_duration_ns BIGINT DEFAULT NULL,
                eval_tokens INT DEFAULT NULL,
                eval_duration_ns BIGINT DEFAULT NULL,
                load_duration_ns BIGINT DEFAULT NULL,
                total_duration_ns BIGINT DEFAULT NULL,
                succeeded BOOLEAN NOT NULL,
                error_kind VARCHAR(32) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        $this->addSql('CREATE INDEX idx_ai_call_metric_feature_created ON ai_call_metric (feature, created_at)');
        $this->addSql('CREATE INDEX idx_ai_call_metric_model_created ON ai_call_metric (model, created_at)');
    }

    public function down(Schema $schema): void
    {
        // The indexes go with the table; naming them here would only be a
        // second thing to keep in step.
        $this->addSql('DROP TABLE ai_call_metric');
    }
}
