<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260729080943 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Make labels user-scoped and move every provider link onto a new label_binding table — one row per (label, account) carrying the IMAP folder, Gmail label id and Graph folder id. Existing label data is discarded and re-synced from the providers.';
    }

    public function up(Schema $schema): void
    {
        // Destructive by design. label.account_id is repurposed as usr_id, so
        // leaving rows behind would silently reinterpret account ids as user
        // ids. Labels are fully reconstructible from the providers, so the
        // cheapest correct migration is to drop them and let sync refill.
        // CASCADE also clears message_label / thread_label.
        $this->addSql('TRUNCATE TABLE label CASCADE');

        $this->addSql(<<<'SQL'
            CREATE TABLE label_binding (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              gmail_label_id VARCHAR(255) DEFAULT NULL,
              graph_folder_id VARCHAR(512) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              label_id INT NOT NULL,
              account_id INT NOT NULL,
              mailbox_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_EFD79E0C33B92F39 ON label_binding (label_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EFD79E0C66EC35CC ON label_binding (mailbox_id)');
        $this->addSql('CREATE INDEX idx_label_binding_gmail_label_id ON label_binding (gmail_label_id)');
        $this->addSql('CREATE INDEX idx_label_binding_graph_folder_id ON label_binding (graph_folder_id)');
        $this->addSql('CREATE INDEX idx_label_binding_account ON label_binding (account_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_label_binding_label_account ON label_binding (label_id, account_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              label_binding
            ADD
              CONSTRAINT FK_EFD79E0C33B92F39 FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              label_binding
            ADD
              CONSTRAINT FK_EFD79E0C9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              label_binding
            ADD
              CONSTRAINT FK_EFD79E0C66EC35CC FOREIGN KEY (mailbox_id) REFERENCES mailbox (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);

        $this->addSql('ALTER TABLE label DROP CONSTRAINT fk_ea750e89b6b5fba');
        $this->addSql('DROP INDEX idx_label_account');
        $this->addSql('DROP INDEX idx_label_gmail_label_id');
        $this->addSql('ALTER TABLE label DROP gmail_label_id');
        $this->addSql('ALTER TABLE label DROP graph_folder_id');
        $this->addSql('ALTER TABLE label RENAME COLUMN account_id TO usr_id');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              label
            ADD
              CONSTRAINT FK_EA750E8C69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql('CREATE INDEX idx_label_usr ON label (usr_id)');

        // Sibling-name uniqueness stays at the service layer (LabelResolver's
        // find-or-create). Expressing it here needs a partial index — NULL
        // parent_id never equals itself, so a plain unique index would let
        // duplicate root labels through — and a partial index is invisible to
        // Doctrine's mapping, which puts doctrine:schema:validate permanently
        // out of sync. That tradeoff predates this change.

        // The folder link now lives on label_binding.mailbox_id.
        $this->addSql('ALTER TABLE mailbox DROP CONSTRAINT fk_a69fe20b33b92f39');
        $this->addSql('DROP INDEX idx_a69fe20b33b92f39');
        $this->addSql('ALTER TABLE mailbox DROP label_id');
    }

    public function down(Schema $schema): void
    {
        // Equally destructive in reverse: per-account labels cannot be
        // reconstructed from user-scoped ones without inventing rows.
        $this->addSql('TRUNCATE TABLE label CASCADE');

        $this->addSql('ALTER TABLE label_binding DROP CONSTRAINT FK_EFD79E0C33B92F39');
        $this->addSql('ALTER TABLE label_binding DROP CONSTRAINT FK_EFD79E0C9B6B5FBA');
        $this->addSql('ALTER TABLE label_binding DROP CONSTRAINT FK_EFD79E0C66EC35CC');
        $this->addSql('DROP TABLE label_binding');

        $this->addSql('ALTER TABLE label DROP CONSTRAINT FK_EA750E8C69D3FB');
        $this->addSql('DROP INDEX idx_label_usr');
        $this->addSql('ALTER TABLE label ADD gmail_label_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE label ADD graph_folder_id VARCHAR(512) DEFAULT NULL');
        $this->addSql('ALTER TABLE label RENAME COLUMN usr_id TO account_id');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              label
            ADD
              CONSTRAINT fk_ea750e89b6b5fba FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('CREATE INDEX idx_label_account ON label (account_id)');
        $this->addSql('CREATE INDEX idx_label_gmail_label_id ON label (gmail_label_id)');
        $this->addSql('ALTER TABLE mailbox ADD label_id INT DEFAULT NULL');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              mailbox
            ADD
              CONSTRAINT fk_a69fe20b33b92f39 FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE
            SET
              NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('CREATE INDEX idx_a69fe20b33b92f39 ON mailbox (label_id)');
    }
}
