<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260727203709 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add uploaded_blob — holding area for JMAP blob uploads.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE uploaded_blob (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, content_type VARCHAR(255) NOT NULL, size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_88ED64819B6B5FBA ON uploaded_blob (account_id)');
        $this->addSql('CREATE INDEX idx_uploaded_blob_created ON uploaded_blob (created_at)');
        $this->addSql('ALTER TABLE uploaded_blob ADD CONSTRAINT FK_88ED64819B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE uploaded_blob DROP CONSTRAINT FK_88ED64819B6B5FBA');
        $this->addSql('DROP TABLE uploaded_blob');
    }
}
