<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The OAuth app registration behind mail sign-in, moved out of env-only config.
 *
 * Adds no data: OAuthProviderFactory reads a row here first and falls back to
 * GOOGLE_OAUTH_* / MICROSOFT_OAUTH_*, so an installation configured through .env
 * carries on unchanged and only starts using the table once an admin edits the
 * values in the UI.
 *
 * client_secret is plain TEXT because encrypted_string is an application-side
 * Doctrine type — the ciphertext lands in an ordinary column and needs no
 * special DDL, at the cost of never being searchable in SQL.
 */
final class Version20260730013525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create mail_provider_config for admin-editable mail OAuth credentials';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mail_provider_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(32) NOT NULL, client_id VARCHAR(255) DEFAULT NULL, client_secret TEXT DEFAULT NULL, settings JSONB NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_mail_provider_config_provider ON mail_provider_config (provider)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE mail_provider_config');
    }
}
