<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Sharing a calendar without an account, and letting a stranger book an hour of
 * it.
 *
 * Five tables and one of them is the whole point. calendar_booking exists first
 * as a constraint and only second as a record: uniq_calendar_booking_page_start
 * is what stops two people taking the same slot, and it is the only mechanism
 * that can, because every check performed in PHP happens before the write and
 * therefore before the other request's write. Two people pressing Book at the
 * same instant both read a free slot; Postgres is the only participant that
 * sees both inserts. Dropping that index would leave an application that looks
 * identical and double-books under exactly the load that matters.
 *
 * The two token columns are hex SHA-256 and are NOT the tokens. A share link
 * and a booking page are gated by a string in a URL and nothing else, which
 * makes that string a credential; storing it would put a working key to
 * somebody's diary in every backup, for as long as the link lives. The same
 * reasoning DevicePairingService gives for hashing its pairing codes, applied
 * to a secret that lasts until it is revoked rather than two minutes. Both
 * columns are UNIQUE because every unauthenticated request resolves to exactly
 * one row by the digest alone — two rows sharing one would make a URL
 * ambiguous.
 *
 * calendar_booking.event_id cascades, and that cascade is a feature rather than
 * bookkeeping: deleting the meeting is how an owner cancels a booking, and the
 * row holding the slot has to go with it or the hour stays unbookable forever.
 * It is also what keeps a stranger's name and address from outliving the
 * appointment they gave them for.
 *
 * calendar_share_link.window_mode is spelled with the suffix because WINDOW is
 * reserved in Postgres. A column called "window" works only while every
 * statement that names it remembers the quotes.
 *
 * Five new tables and no backfill: an install upgrading to this has no links,
 * no pages and no bookings, and it must not invent any. Nothing existing is
 * altered, so this is additive and reversible — down() drops the five tables
 * and loses only what was created through the new screens.
 */
final class Version20260805161859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add shareable calendar links, booking pages and the bookings they take';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE booking_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, token_digest VARCHAR(64) NOT NULL, is_enabled BOOLEAN DEFAULT true NOT NULL, time_zone VARCHAR(64) DEFAULT \'UTC\' NOT NULL, weekdays JSONB DEFAULT \'[]\' NOT NULL, start_minute SMALLINT DEFAULT 540 NOT NULL, end_minute SMALLINT DEFAULT 1020 NOT NULL, slot_minutes SMALLINT DEFAULT 30 NOT NULL, buffer_minutes SMALLINT DEFAULT 0 NOT NULL, notice_minutes INT DEFAULT 120 NOT NULL, horizon_days INT DEFAULT 30 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_id INT NOT NULL, calendar_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C9B946EA40A2C8 ON booking_page (calendar_id)');
        $this->addSql('CREATE INDEX idx_booking_page_usr ON booking_page (usr_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_booking_page_token_digest ON booking_page (token_digest)');
        $this->addSql('CREATE TABLE booking_page_calendar (booking_page_id INT NOT NULL, calendar_id INT NOT NULL, PRIMARY KEY (booking_page_id, calendar_id))');
        $this->addSql('CREATE INDEX IDX_E50FE6A656F826C4 ON booking_page_calendar (booking_page_id)');
        $this->addSql('CREATE INDEX IDX_E50FE6A6A40A2C8 ON booking_page_calendar (calendar_id)');
        $this->addSql('CREATE TABLE calendar_booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booker_name VARCHAR(120) NOT NULL, booker_email VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, booker_time_zone VARCHAR(64) DEFAULT \'UTC\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_page_id INT NOT NULL, usr_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_827B961956F826C4 ON calendar_booking (booking_page_id)');
        $this->addSql('CREATE INDEX IDX_827B9619C69D3FB ON calendar_booking (usr_id)');
        $this->addSql('CREATE INDEX idx_calendar_booking_usr_starts ON calendar_booking (usr_id, starts_at)');
        // The guarantee. Page leads because every read of this table is scoped
        // to one page, and starts_at second so the same index answers "which
        // slots in this window are taken" — the query every public GET makes.
        $this->addSql('CREATE UNIQUE INDEX uniq_calendar_booking_page_start ON calendar_booking (booking_page_id, starts_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_calendar_booking_event ON calendar_booking (event_id)');
        $this->addSql('CREATE TABLE calendar_share_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, token_digest VARCHAR(64) NOT NULL, details JSONB DEFAULT \'[]\' NOT NULL, window_mode VARCHAR(16) DEFAULT \'rolling\' NOT NULL, rolling_days INT DEFAULT 14 NOT NULL, starts_on DATE DEFAULT NULL, ends_on DATE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_viewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_calendar_share_link_usr ON calendar_share_link (usr_id)');
        // The public lookup, and the collision guard on the mint. Unique rather
        // than plain because a URL that resolved to two links would answer with
        // whichever diary the planner reached first.
        $this->addSql('CREATE UNIQUE INDEX uniq_calendar_share_link_token_digest ON calendar_share_link (token_digest)');
        $this->addSql('CREATE TABLE calendar_share_link_calendar (share_link_id INT NOT NULL, calendar_id INT NOT NULL, PRIMARY KEY (share_link_id, calendar_id))');
        $this->addSql('CREATE INDEX IDX_6EE1527EEFC8A8ED ON calendar_share_link_calendar (share_link_id)');
        $this->addSql('CREATE INDEX IDX_6EE1527EA40A2C8 ON calendar_share_link_calendar (calendar_id)');
        $this->addSql('ALTER TABLE booking_page ADD CONSTRAINT FK_C9B946EC69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking_page ADD CONSTRAINT FK_C9B946EA40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking_page_calendar ADD CONSTRAINT FK_E50FE6A656F826C4 FOREIGN KEY (booking_page_id) REFERENCES booking_page (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking_page_calendar ADD CONSTRAINT FK_E50FE6A6A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_booking ADD CONSTRAINT FK_827B961956F826C4 FOREIGN KEY (booking_page_id) REFERENCES booking_page (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_booking ADD CONSTRAINT FK_827B9619C69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_booking ADD CONSTRAINT FK_827B961971F7E88B FOREIGN KEY (event_id) REFERENCES calendar_event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_share_link ADD CONSTRAINT FK_1D21506DC69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_share_link_calendar ADD CONSTRAINT FK_6EE1527EEFC8A8ED FOREIGN KEY (share_link_id) REFERENCES calendar_share_link (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_share_link_calendar ADD CONSTRAINT FK_6EE1527EA40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE booking_page DROP CONSTRAINT FK_C9B946EC69D3FB');
        $this->addSql('ALTER TABLE booking_page DROP CONSTRAINT FK_C9B946EA40A2C8');
        $this->addSql('ALTER TABLE booking_page_calendar DROP CONSTRAINT FK_E50FE6A656F826C4');
        $this->addSql('ALTER TABLE booking_page_calendar DROP CONSTRAINT FK_E50FE6A6A40A2C8');
        $this->addSql('ALTER TABLE calendar_booking DROP CONSTRAINT FK_827B961956F826C4');
        $this->addSql('ALTER TABLE calendar_booking DROP CONSTRAINT FK_827B9619C69D3FB');
        $this->addSql('ALTER TABLE calendar_booking DROP CONSTRAINT FK_827B961971F7E88B');
        $this->addSql('ALTER TABLE calendar_share_link DROP CONSTRAINT FK_1D21506DC69D3FB');
        $this->addSql('ALTER TABLE calendar_share_link_calendar DROP CONSTRAINT FK_6EE1527EEFC8A8ED');
        $this->addSql('ALTER TABLE calendar_share_link_calendar DROP CONSTRAINT FK_6EE1527EA40A2C8');
        $this->addSql('DROP TABLE booking_page');
        $this->addSql('DROP TABLE booking_page_calendar');
        $this->addSql('DROP TABLE calendar_booking');
        $this->addSql('DROP TABLE calendar_share_link');
        $this->addSql('DROP TABLE calendar_share_link_calendar');
    }
}
