<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * One row that says whether a backfill is meant to be walking, and where it got
 * to.
 *
 * WHAT IS NOT IN HERE
 * ───────────────────
 * A count of embedded messages. That number is a query against
 * message_embedding — the vectors themselves ARE the progress record — so a
 * worker killed mid-chunk resumes where they stop rather than where a counter
 * last managed to be written. Storing it as well would create two versions of
 * one fact, and they would disagree exactly when somebody was watching.
 *
 * WHY A SINGLETON AND NOT A ROW PER RUN
 * ─────────────────────────────────────
 * There is only ever one backfill: it is a pass over every mailbox on an
 * installation, competing for one model host. A history of past runs would be
 * a second thing to prune and would answer no question anybody asks — "how far
 * has it got" is about the run happening now, and "is my mail searchable" is
 * answered by the vectors.
 *
 * The per-mailbox cursors live in `mailboxes` as jsonb rather than in a child
 * table, following User::$settings and Account::$settings. They are written
 * with jsonb_set from the worker, one key at a time, so two mailboxes being
 * walked cannot lose each other's position — which is the only concurrency
 * this row has.
 *
 * interactive_seen_at IS HERE BECAUSE THE TWO SIDES SHARE NOTHING ELSE
 * ────────────────────────────────────────────────────────────────────
 * The web container stamps it when somebody starts using the composer or the
 * search; the maintenance worker reads it before every batch and steps aside
 * if it is recent. They are different processes in different containers, and
 * the database is the only thing between them that survives a restart. A cache
 * would work until the day the two were not sharing one.
 */
final class Version20260828000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add ai_backfill_state: whether the embedding backfill is walking, and where it got to.';
    }

    public function up(Schema $schema): void
    {
        // `GENERATED BY DEFAULT AS IDENTITY`, as ai_call_metric and
        // background_job do it. ai_settings' SERIAL is the outlier.
        $this->addSql(<<<'SQL'
            CREATE TABLE ai_backfill_state (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                singleton INT DEFAULT 1 NOT NULL,
                status VARCHAR(16) DEFAULT 'idle' NOT NULL,
                pause_reason VARCHAR(32) DEFAULT NULL,
                model VARCHAR(128) DEFAULT NULL,
                mailboxes JSONB DEFAULT '{}' NOT NULL,
                failures INT DEFAULT 0 NOT NULL,
                empty_batches INT DEFAULT 0 NOT NULL,
                last_error VARCHAR(32) DEFAULT NULL,
                started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                last_progress_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                interactive_seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        // The index is what enforces "one row", not a check in PHP — every such
        // check happens before the insert, and therefore before another
        // process's insert. Two workers coming up together both find the table
        // empty; only one of them gets the row. Same reasoning as
        // uniq_ai_settings_singleton.
        $this->addSql('CREATE UNIQUE INDEX uniq_ai_backfill_state_singleton ON ai_backfill_state (singleton)');

        // The backfill's rate is "vectors written in the last five minutes",
        // which the admin panel polls. Without this it is a scan of every
        // embedding on the installation every few seconds — and the table it
        // scans is the one the backfill is filling.
        $this->addSql('CREATE INDEX idx_message_embedding_created ON message_embedding (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX IF EXISTS idx_message_embedding_created');
        // The unique index goes with the table; naming it here would only be a
        // second thing to keep in step.
        $this->addSql('DROP TABLE ai_backfill_state');
    }
}
