<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A date read out of prose is a guess, and a guess needs somewhere to live that
 * is not the calendar.
 *
 * The obvious alternative was a flag on calendar_event — "pending", "proposed",
 * one more state beside cancelled. It was rejected because of how the calendar
 * is read: CalendarEventWriter materialises occurrences on every write, every
 * range query reads occurrences, and the topbar's upcoming-event dot is lit
 * from them. An event row is visible by construction, so a proposal kept there
 * would be visible unless every one of those readers remembered to exclude it —
 * and the one that forgot would put an invented appointment on somebody's
 * calendar without anything looking wrong. A separate table materialises no
 * occurrences and therefore cannot leak.
 *
 * Accepting a proposal writes a real event through the ordinary path and drops
 * the row; refusing writes an event_suppression row, which is the mechanism
 * dismissal already uses for extracted events, and is why nothing here needs a
 * "dismissed" state either. A proposal is therefore short-lived by design and
 * this table stays small.
 *
 * source_sentence is not optional and not decoration: the card quotes it, and a
 * guess whose evidence is visible can be judged at a glance where a bare date
 * with an Add button cannot. dedup_key_hash is the same char(64) shape
 * event_suppression stores, so a refusal recorded here matches on the next
 * detection run without a conversion anywhere.
 *
 * One unique index, on (message_id, starts_at). A message may not propose the
 * same instant twice — the proposer checks first, but that check is a read on
 * data a concurrent backfill may be about to change, and this is the guard that
 * actually holds. The message leads because every read of this table starts
 * from a message: the card asks per conversation, and both actions are keyed on
 * a message someone is looking at.
 *
 * The two IDX_ indexes are Doctrine's own foreign-key indexes. The one on
 * message_id is covered by the unique index above and is kept anyway, because
 * removing it makes `doctrine:schema:update --dump-sql` want it back on every
 * run, and a schema that reports permanent drift is a schema nobody reads.
 *
 * Reversible, and losing nothing that matters: an un-answered proposal is an
 * offer nobody accepted, and the next detection run makes it again.
 */
final class Version20260804120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Give a date read out of prose somewhere to wait that is not the calendar';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE event_proposal (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title TEXT NOT NULL,
                starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                is_all_day BOOLEAN DEFAULT false NOT NULL,
                time_zone VARCHAR(64) DEFAULT NULL,
                confidence SMALLINT DEFAULT 0 NOT NULL,
                source_sentence TEXT NOT NULL,
                dedup_key_hash CHAR(64) NOT NULL,
                detector VARCHAR(32) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                usr_id INT NOT NULL,
                message_id INT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_F9097DA2C69D3FB ON event_proposal (usr_id)');
        $this->addSql('CREATE INDEX IDX_F9097DA2537A1329 ON event_proposal (message_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_proposal_message_starts_at ON event_proposal (message_id, starts_at)');
        $this->addSql('ALTER TABLE event_proposal ADD CONSTRAINT FK_F9097DA2C69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_proposal ADD CONSTRAINT FK_F9097DA2537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE event_proposal DROP CONSTRAINT FK_F9097DA2537A1329');
        $this->addSql('ALTER TABLE event_proposal DROP CONSTRAINT FK_F9097DA2C69D3FB');
        $this->addSql('DROP TABLE event_proposal');
    }
}
