<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Events gain alerts, and alerts gain somewhere to record that they have already
 * gone off.
 *
 * The alerts themselves need no schema at all: they live in the event's
 * canonical JSCalendar object under `alerts` (RFC 8984 §4.5.2), which is the
 * whole reason that column is jsonb rather than a set of hand-picked fields — an
 * alert round-trips to Google, Graph and CalDAV because it is stored in the
 * vocabulary those three convert to, not because plMail invented a column for
 * it. Nothing queries an alert's offset, so nothing is projected out.
 *
 * What does need a table is the fact that one has fired. An alert must go off
 * exactly once, and every way of losing that is a way that happens in
 * production: two sweeps overlapping when the first ran long, the scheduler
 * replaying a missed run after a worker restart, a container killed between
 * sending the push and writing down that it sent one. A flag on the event cannot
 * say "the 09:00 instance was alerted and tomorrow's 09:00 was not", and a
 * comment saying not to send twice is not a guarantee. A unique constraint is.
 *
 * The row is keyed by (event, alert key, recurrence id) and NOT by the
 * occurrence's own id, which is the detail that makes it work.
 * RecurrenceMaterialiser rewrites an event's occurrence rows wholesale on every
 * write, so a foreign key to one would cascade this record away every time
 * somebody corrected a title — and the alert would fire again on the next sweep.
 * The recurrence id is the instance's identity: where the rule put it before
 * anything moved it, and stable across every re-materialisation.
 *
 * A new table with no backfill: an install upgrading to this has no delivery
 * history to reconstruct, and it must not invent one. What stops the first sweep
 * delivering a year of past reminders is not this table — it is empty either way
 * — but the lookback window in DueAlertReader, which refuses any trigger more
 * than an hour old.
 *
 * It also gives calendar_event_occurrence a start-only index. That table already
 * has two, and neither can serve this: both lead with usr_id or calendar_id,
 * because every other read of an occurrence is scoped to somebody. The alert
 * sweep is the one read that is not — it asks what starts near now across the
 * whole install, once a minute — so without this index it reads every occurrence
 * row that has ever been materialised, and an unbounded recurring event is a
 * thousand of those on its own.
 *
 * Reversible, and losing only the record of what has already been delivered.
 * Dropping it during the hour after an alert fired would let that one alert fire
 * a second time; outside that hour it costs nothing.
 */
final class Version20260805140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Record that a calendar alert has fired, so it cannot fire twice';
    }

    public function up(Schema $schema): void
    {
        // The sweep's own index, and the reason it is not one of the two this
        // table already has: both of those lead with usr_id or calendar_id,
        // because every other read of occurrences is scoped to somebody. The
        // alert sweep is not — it asks what starts near now across the whole
        // install — so it can use neither, and without this it reads every
        // occurrence row ever materialised once a minute.
        $this->addSql('CREATE INDEX idx_ceo_starts ON calendar_event_occurrence (starts_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE calendar_alert_delivery (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                event_id INT NOT NULL,
                usr_id INT NOT NULL,
                alert_key VARCHAR(255) NOT NULL,
                recurrence_id TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                trigger_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        // The guarantee itself. Everything else in this migration is
        // bookkeeping around this one line.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_calendar_alert_delivery_event_alert_instance
                ON calendar_alert_delivery (event_id, alert_key, recurrence_id)
            SQL);

        // What the prune reads, and the only query here not scoped to an event.
        $this->addSql('CREATE INDEX idx_calendar_alert_delivery_trigger ON calendar_alert_delivery (trigger_at)');

        // Both cascade: a deleted event has no occurrences left to alert about,
        // and a deleted user has no devices to alert. Keeping the records would
        // leave rows that can never be consulted and can never be cleaned up by
        // anything that knows what they meant.
        $this->addSql(<<<'SQL'
            ALTER TABLE calendar_alert_delivery
                ADD CONSTRAINT fk_calendar_alert_delivery_event
                FOREIGN KEY (event_id) REFERENCES calendar_event (id)
                ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE calendar_alert_delivery
                ADD CONSTRAINT fk_calendar_alert_delivery_usr
                FOREIGN KEY (usr_id) REFERENCES "user" (id)
                ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE calendar_alert_delivery');
        $this->addSql('DROP INDEX idx_ceo_starts');
    }
}
