<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The calendar: calendars, events, their materialised occurrences, and the
 * provenance tables extraction will write to.
 *
 * Nothing to backfill. Existing users get their default and per-account
 * calendars from `app:backfill calendars`, not from here — provisioning is
 * application logic that has to agree with what AccountCreator does for new
 * accounts, and duplicating it in SQL would be two implementations of "what
 * calendars should exist" that drift.
 *
 * Two things here are not Doctrine's doing and will not survive a
 * `doctrine:migrations:diff` that regenerates this file:
 *
 *   btree_gist, and the GiST index over (calendar_id, span). Every calendar
 *   view is a range overlap — `span && tsrange(from, to)` — and that is what
 *   answers it. The index is composite because a view reads a set of
 *   calendars, and an int column cannot go into a GiST index without
 *   btree_gist. The extension also gets used again by the appointment
 *   manager's no-double-booking exclusion constraint.
 *
 *   span itself is GENERATED ALWAYS, declared via columnDefinition on the
 *   entity, so Postgres maintains it and it cannot drift from the two columns
 *   it derives from — the same treatment message.search_vector gets.
 *
 * cache_items is deliberately absent despite showing up in the diff: the DBAL
 * cache adapter creates that table itself on first write and owns its DDL.
 */
final class Version20260731222453 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add calendars, events, materialised occurrences and event provenance';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE calendar (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, color VARCHAR(7) DEFAULT \'#2563eb\' NOT NULL, time_zone VARCHAR(64) DEFAULT \'UTC\' NOT NULL, role VARCHAR(20) DEFAULT \'custom\' NOT NULL, is_visible BOOLEAN DEFAULT true NOT NULL, is_default BOOLEAN DEFAULT false NOT NULL, is_read_only BOOLEAN DEFAULT false NOT NULL, sort_order INT DEFAULT 0 NOT NULL, remote_id VARCHAR(255) DEFAULT NULL, sync_token TEXT DEFAULT NULL, settings JSONB DEFAULT \'{}\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_id INT NOT NULL, account_id INT DEFAULT NULL, integration_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EA9A1469E82DDEA ON calendar (integration_id)');
        $this->addSql('CREATE INDEX idx_calendar_usr ON calendar (usr_id)');
        $this->addSql('CREATE INDEX idx_calendar_account ON calendar (account_id)');
        $this->addSql('CREATE TABLE calendar_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid VARCHAR(255) NOT NULL, sequence INT DEFAULT 0 NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, time_zone VARCHAR(64) DEFAULT NULL, is_all_day BOOLEAN DEFAULT false NOT NULL, title TEXT DEFAULT NULL, location TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'confirmed\' NOT NULL, privacy VARCHAR(16) DEFAULT \'public\' NOT NULL, kind VARCHAR(24) DEFAULT NULL, source VARCHAR(20) DEFAULT \'manual\' NOT NULL, confidence SMALLINT DEFAULT 100 NOT NULL, is_recurring BOOLEAN DEFAULT false NOT NULL, recurrence_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_user_edited BOOLEAN DEFAULT false NOT NULL, dedup_key_version SMALLINT DEFAULT 1 NOT NULL, jscalendar JSONB DEFAULT \'{}\' NOT NULL, remote_id VARCHAR(255) DEFAULT NULL, remote_etag VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, calendar_id INT NOT NULL, usr_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57FA09C9A40A2C8 ON calendar_event (calendar_id)');
        $this->addSql('CREATE INDEX idx_calendar_event_usr ON calendar_event (usr_id)');
        $this->addSql('CREATE INDEX idx_calendar_event_calendar_starts ON calendar_event (calendar_id, starts_at)');
        $this->addSql('CREATE INDEX idx_calendar_event_uid ON calendar_event (uid)');
        $this->addSql('CREATE INDEX idx_calendar_event_kind ON calendar_event (kind)');
        $this->addSql('CREATE UNIQUE INDEX uniq_calendar_event_calendar_uid ON calendar_event (calendar_id, uid)');
        $this->addSql('CREATE TABLE calendar_event_occurrence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recurrence_id TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_override BOOLEAN DEFAULT false NOT NULL, cancelled BOOLEAN DEFAULT false NOT NULL, span tsrange GENERATED ALWAYS AS (tsrange(starts_at, ends_at, \'[)\')) STORED, event_id INT NOT NULL, calendar_id INT NOT NULL, usr_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A77CFB6F71F7E88B ON calendar_event_occurrence (event_id)');
        $this->addSql('CREATE INDEX IDX_A77CFB6FA40A2C8 ON calendar_event_occurrence (calendar_id)');
        $this->addSql('CREATE INDEX IDX_A77CFB6FC69D3FB ON calendar_event_occurrence (usr_id)');
        $this->addSql('CREATE INDEX idx_ceo_usr_starts ON calendar_event_occurrence (usr_id, starts_at)');
        $this->addSql('CREATE INDEX idx_ceo_calendar_starts ON calendar_event_occurrence (calendar_id, starts_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ceo_event_recurrence ON calendar_event_occurrence (event_id, recurrence_id)');

        // The index every calendar view actually uses. btree_gist is what lets
        // an int sit beside a range in one GiST index; without it this has to
        // become two indexes and the planner stops being able to use both.
        $this->addSql('CREATE EXTENSION IF NOT EXISTS btree_gist');
        $this->addSql('CREATE INDEX idx_ceo_span ON calendar_event_occurrence USING gist (calendar_id, span)');

        $this->addSql('CREATE TABLE event_source_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, extractor VARCHAR(64) NOT NULL, confidence SMALLINT DEFAULT 0 NOT NULL, dedup_key VARCHAR(128) NOT NULL, applied BOOLEAN DEFAULT true NOT NULL, payload JSONB DEFAULT \'{}\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT NOT NULL, message_id INT NOT NULL, message_part_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9CAFCF7271F7E88B ON event_source_link (event_id)');
        $this->addSql('CREATE INDEX IDX_9CAFCF72DC6B71E0 ON event_source_link (message_part_id)');
        $this->addSql('CREATE INDEX idx_event_source_link_message ON event_source_link (message_id)');
        $this->addSql('CREATE INDEX idx_event_source_link_dedup ON event_source_link (dedup_key)');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_source_link ON event_source_link (event_id, message_id, extractor)');
        $this->addSql('CREATE TABLE event_suppression (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dedup_key_hash CHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_24B19C69D3FB ON event_suppression (usr_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_suppression ON event_suppression (usr_id, dedup_key_hash)');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A146C69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A1469B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar ADD CONSTRAINT FK_6EA9A1469E82DDEA FOREIGN KEY (integration_id) REFERENCES integration (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9A40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C9C69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event_occurrence ADD CONSTRAINT FK_A77CFB6F71F7E88B FOREIGN KEY (event_id) REFERENCES calendar_event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event_occurrence ADD CONSTRAINT FK_A77CFB6FA40A2C8 FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event_occurrence ADD CONSTRAINT FK_A77CFB6FC69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_source_link ADD CONSTRAINT FK_9CAFCF7271F7E88B FOREIGN KEY (event_id) REFERENCES calendar_event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_source_link ADD CONSTRAINT FK_9CAFCF72537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_source_link ADD CONSTRAINT FK_9CAFCF72DC6B71E0 FOREIGN KEY (message_part_id) REFERENCES message_part (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_suppression ADD CONSTRAINT FK_24B19C69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE calendar DROP CONSTRAINT FK_6EA9A146C69D3FB');
        $this->addSql('ALTER TABLE calendar DROP CONSTRAINT FK_6EA9A1469B6B5FBA');
        $this->addSql('ALTER TABLE calendar DROP CONSTRAINT FK_6EA9A1469E82DDEA');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9A40A2C8');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C9C69D3FB');
        $this->addSql('ALTER TABLE calendar_event_occurrence DROP CONSTRAINT FK_A77CFB6F71F7E88B');
        $this->addSql('ALTER TABLE calendar_event_occurrence DROP CONSTRAINT FK_A77CFB6FA40A2C8');
        $this->addSql('ALTER TABLE calendar_event_occurrence DROP CONSTRAINT FK_A77CFB6FC69D3FB');
        $this->addSql('ALTER TABLE event_source_link DROP CONSTRAINT FK_9CAFCF7271F7E88B');
        $this->addSql('ALTER TABLE event_source_link DROP CONSTRAINT FK_9CAFCF72537A1329');
        $this->addSql('ALTER TABLE event_source_link DROP CONSTRAINT FK_9CAFCF72DC6B71E0');
        $this->addSql('ALTER TABLE event_suppression DROP CONSTRAINT FK_24B19C69D3FB');
        $this->addSql('DROP TABLE event_suppression');
        $this->addSql('DROP TABLE event_source_link');
        $this->addSql('DROP TABLE calendar_event_occurrence');
        $this->addSql('DROP TABLE calendar_event');
        $this->addSql('DROP TABLE calendar');

        // btree_gist is left installed on purpose: dropping an extension other
        // features may already depend on is not this migration's business.
    }
}
