<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260726155733 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create jmap_change_log, the append-only JMAP state/change log.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE jmap_change_log (sequence INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_id INT NOT NULL, object_type VARCHAR(32) NOT NULL, entity_id VARCHAR(64) NOT NULL, change_type VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (sequence))');
        $this->addSql('CREATE INDEX idx_jmap_change_scan ON jmap_change_log (account_id, object_type, sequence)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE jmap_change_log');
    }
}
