<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Integrations: per-user connections to external file and photo services, and
 * the admin-owned provider setup behind them.
 *
 * Credential columns (secret, oauth_access_token, oauth_refresh_token,
 * client_secret) are plain TEXT here — encrypted_string is an application-side
 * Doctrine type, so the ciphertext lands in an ordinary text column and needs
 * no special DDL. It also means those columns are never searchable or
 * comparable in SQL, which is why secret_hint exists alongside secret.
 */
final class Version20260729134208 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create integration and integration_provider_config tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE integration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(32) NOT NULL, name VARCHAR(100) NOT NULL, base_url VARCHAR(512) DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, secret TEXT DEFAULT NULL, secret_hint VARCHAR(16) DEFAULT NULL, oauth_access_token TEXT DEFAULT NULL, oauth_refresh_token TEXT DEFAULT NULL, oauth_token_expiry TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, settings JSONB NOT NULL, last_checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usr_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_integration_user ON integration (usr_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_integration_user_provider_name ON integration (usr_id, provider, name)');
        $this->addSql('CREATE TABLE integration_provider_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(32) NOT NULL, is_enabled BOOLEAN NOT NULL, base_url VARCHAR(512) DEFAULT NULL, client_id VARCHAR(255) DEFAULT NULL, client_secret TEXT DEFAULT NULL, settings JSONB NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_integration_provider_config_provider ON integration_provider_config (provider)');
        $this->addSql('ALTER TABLE integration ADD CONSTRAINT FK_FDE96D9BC69D3FB FOREIGN KEY (usr_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE integration DROP CONSTRAINT FK_FDE96D9BC69D3FB');
        $this->addSql('DROP TABLE integration');
        $this->addSql('DROP TABLE integration_provider_config');
    }
}
