<?php

declare(strict_types=1);

namespace App\Tests\Infrastructure\Messaging\Handler;

use App\Domain\Enum\Account\AuthType;
use App\Domain\Enum\Account\MailProvider;
use App\Domain\Enum\Calendar\CalendarRole;
use App\Domain\Enum\Integration\Provider;
use App\Entity\Calendar\Calendar;
use App\Entity\Integration\Integration;
use App\Entity\Mail\Account;
use App\Entity\User\User;
use App\Infrastructure\Messaging\Handler\RegisterCalendarPushHandler;
use App\Infrastructure\Messaging\Message\RegisterCalendarPushMessage;
use App\Repository\Calendar\CalendarRepository;
use App\Service\Calendar\Push\CalendarPushRegistry;
use App\Service\Calendar\Push\GoogleCalendarPushManager;
use App\Service\Calendar\Push\PushCallbackUrl;
use App\Service\Calendar\Sync\Google\GoogleCalendarApiClient;
use App\Service\OAuth\OAuthTokenManager;
use App\Tests\Service\Calendar\RecordingLogger;
use DateTimeImmutable;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\HttpClient\MockHttpClient;
use Symfony\Component\HttpClient\Response\MockResponse;

/**
 * A calendar that was ticked a second ago should be pushing, not polling — and
 * asking for that must be incapable of costing anything.
 *
 * The claim is the pair. Before this handler existed the hourly sweep was the
 * only thing that opened a channel, so a calendar subscribed at 09:21 polled
 * until 10:20: the feature worked and its first hour looked exactly like it did
 * not, which is the hour somebody is watching to find out.
 *
 * The other half is what this must not do. Registration fails for deployment
 * facts — no public HTTPS address, a Google Cloud project whose domain
 * verification is pending — and a click that depended on the outcome would
 * report one of those as an error on a checkbox and then never retry. So every
 * refusal below is asserted to leave the calendar exactly as the sweep expects
 * to find it: subscribed, polled, and with nothing half-written on it.
 *
 * Against a real container, a real database and a MockHttpClient. The managers
 * and the registry are final and cannot be doubled; the assertions that matter
 * are about requests that must NOT be sent, and the mock is the only place that
 * is observable.
 */
final class RegisterCalendarPushHandlerTest extends KernelTestCase
{
    private const string PUBLIC_URL = 'https://mail.example.test';

    private EntityManagerInterface $em;
    private Connection $connection;
    private CalendarRepository $calendars;
    private PushCallbackUrl $callback;
    private RecordingLogger $logger;
    private User $user;
    private Account $account;
    private Calendar $calendar;

    /** @var list<array{method: string, url: string}> */
    private array $requests = [];

    protected function setUp(): void
    {
        self::bootKernel();

        $container = self::getContainer();

        // PushCallbackUrl resolves the address per call and lets the environment
        // win, so setting it here is enough — and unset again in tearDown,
        // because InstallEmptyInstallTest writes the same key.
        $_SERVER['APP_PUBLIC_URL'] = self::PUBLIC_URL;

        $this->em         = $container->get(EntityManagerInterface::class);
        $this->connection = $container->get(Connection::class);
        $this->calendars  = $container->get(CalendarRepository::class);
        $this->callback   = $container->get(PushCallbackUrl::class);
        $this->logger     = new RecordingLogger();

        $this->connection->beginTransaction();
        $this->seed();
    }

    protected function tearDown(): void
    {
        unset($_SERVER['APP_PUBLIC_URL']);

        if (true === $this->connection->isTransactionActive()) {
            $this->connection->rollBack();
        }

        parent::tearDown();
    }

    public function testAJustSubscribedCalendarGetsItsChannelNowRatherThanOnTheNextSweep(): void
    {
        $handler = $this->handler([$this->watchResponse('res-1', new DateTimeImmutable('+7 days'))]);

        $handler(new RegisterCalendarPushMessage((int) $this->calendar->id));

        self::assertTrue($this->calendar->hasPushChannel(), 'the calendar should be pushing before the hourly sweep runs');
        self::assertSame('res-1', $this->calendar->pushResourceId);
        self::assertNotNull($this->calendar->pushSecret);
        self::assertStringContainsString('/calendars/remote-cal-1/events/watch', $this->requests[0]['url']);
    }

    /**
     * A holiday, birthday or week-number calendar is generated by Google rather
     * than stored, and events.watch answers pushNotSupportedForRequestedResource
     * for every one of them — permanently. GoogleCalendarPushManager records
     * that in the settings bag so the sweep stops offering the calendar; this
     * path has to honour the same answer, or the one thing that stopped an
     * hourly unactionable warning gains a second way to be asked.
     */
    public function testACalendarGoogleHasAlreadyRefusedToWatchIsNotAskedAgainByThisPathEither(): void
    {
        $this->calendar->setSetting('push.unsupported', true);
        $this->em->flush();

        $handler = $this->handler([]);

        $handler(new RegisterCalendarPushMessage((int) $this->calendar->id));

        self::assertSame([], $this->requests, 'a permanent refusal must not be re-asked from the subscribe path');
        self::assertFalse($this->calendar->hasPushChannel());
    }

    public function testAHandMadeLocalCalendarIsNotAskedAtAll(): void
    {
        $local       = new Calendar();
        $local->usr  = $this->user;
        $local->name = 'Personal';
        $local->role = CalendarRole::Custom;
        $this->em->persist($local);
        $this->em->flush();

        $handler = $this->handler([]);

        $handler(new RegisterCalendarPushMessage((int) $local->id));

        self::assertSame([], $this->requests, 'a hand-made calendar has no remote to watch it');
        self::assertFalse($local->hasPushChannel());
    }

    /**
     * CalDAV has no push of any kind, and the calendar carries an account beside
     * the connection often enough that reading the account alone would claim it.
     */
    public function testACalDavCalendarIsNotAskedAtAll(): void
    {
        $integration = new Integration($this->user, Provider::CalDav, 'Fastmail');
        $this->em->persist($integration);

        $caldav              = new Calendar();
        $caldav->usr         = $this->user;
        $caldav->account     = $this->account;
        $caldav->integration = $integration;
        $caldav->name        = 'Shared';
        $caldav->role        = CalendarRole::Remote;
        $caldav->remoteId    = 'https://caldav.example.test/cal/1';
        $this->em->persist($caldav);
        $this->em->flush();

        $handler = $this->handler([]);

        $handler(new RegisterCalendarPushMessage((int) $caldav->id));

        self::assertSame([], $this->requests, 'CalDAV has no channels, whatever account sits beside the connection');
        self::assertFalse($caldav->hasPushChannel());
    }

    public function testARefusedRegistrationLeavesTheCalendarSubscribedAndPollingWithoutRaisingAnything(): void
    {
        // What an unverified callback domain answers with, which is the single
        // most likely outcome on a self-hosted install.
        $handler = $this->handler([new MockResponse(
            json_encode(['error' => ['code' => 403, 'errors' => [['reason' => 'pushNotSupported', 'message' => 'Channel domain not verified']]]], JSON_THROW_ON_ERROR),
            ['http_code' => 403, 'response_headers' => ['content-type' => 'application/json']],
        )]);

        $handler(new RegisterCalendarPushMessage((int) $this->calendar->id));

        self::assertFalse($this->calendar->hasPushChannel(), 'half a registration is worse than none');
        self::assertTrue($this->calendar->isSynced(), 'the calendar stays mirrored and stays on the fifteen-minute sweep');
        self::assertNotSame([], $this->logger->matching('warning', 'staying on polling'), 'the refusal is a log line, never an error');
    }

    /**
     * The transport error a deployment behind a proxy that cannot reach Google
     * produces. It arrives as a thrown exception rather than a status code, and
     * an envelope that let it out would be retried five times and dead-lettered
     * for a calendar that is syncing perfectly well.
     */
    public function testAProviderThatCannotBeReachedAtAllIsStillNotAnError(): void
    {
        $handler = $this->handler([new MockResponse('', ['error' => 'Could not resolve host: www.googleapis.com'])]);

        $handler(new RegisterCalendarPushMessage((int) $this->calendar->id));

        self::assertFalse($this->calendar->hasPushChannel());
    }

    public function testWithNoPublicHttpsAddressNothingIsAskedAndTheReasonIsInTheLog(): void
    {
        $_SERVER['APP_PUBLIC_URL'] = 'http://localhost:8000';

        $handler = $this->handler([]);

        $handler(new RegisterCalendarPushMessage((int) $this->calendar->id));

        self::assertSame([], $this->requests, 'an unreachable install must not spend a request finding that out');
        self::assertFalse($this->calendar->hasPushChannel());

        // The one place a self-hoster learns why the calendar they just ticked
        // is polling. The sweep is silent about this by design — it would say it
        // once an hour per calendar — so this path is where it gets said.
        self::assertNotSame([], $this->logger->matching('warning', 'no usable public HTTPS address'));
    }

    /**
     * Messenger redelivers: a worker killed between the registration and the ack
     * runs the same envelope again. Without the renewal check that second run
     * would open a fresh channel and stop the live one, for nothing.
     */
    public function testACalendarThatAlreadyHasALiveChannelIsLeftAlone(): void
    {
        $this->calendar->pushChannelId  = 'chan-1';
        $this->calendar->pushResourceId = 'res-1';
        $this->calendar->pushSecret     = 'secret';
        $this->calendar->pushExpiresAt  = new DateTimeImmutable('+6 days');
        $this->em->flush();

        $handler = $this->handler([]);

        $handler(new RegisterCalendarPushMessage((int) $this->calendar->id));

        self::assertSame([], $this->requests);
        self::assertSame('chan-1', $this->calendar->pushChannelId, 'a redelivery must not replace a channel that is working');
    }

    public function testACalendarUnsubscribedBeforeTheRegistrationRanIsNothingToDo(): void
    {
        $id = (int) $this->calendar->id;

        $this->em->remove($this->calendar);
        $this->em->flush();

        $handler = $this->handler([]);

        $handler(new RegisterCalendarPushMessage($id));

        self::assertSame([], $this->requests, 'a calendar unticked before the worker got to it is normal, not an error');
    }

    // ── Fixture ──────────────────────────────────────────────────────────────

    /**
     * @param list<MockResponse> $responses
     */
    private function handler(array $responses): RegisterCalendarPushHandler
    {
        $http = new MockHttpClient(function (string $method, string $url) use (&$responses): MockResponse {
            $this->requests[] = ['method' => $method, 'url' => $url];

            $response = array_shift($responses);

            self::assertNotNull($response, sprintf('unexpected request: %s %s', $method, $url));

            return $response;
        });

        $tokens = $this->createStub(OAuthTokenManager::class);
        $tokens->method('getValidAccessToken')->willReturn('test-token');

        $manager = new GoogleCalendarPushManager(
            new GoogleCalendarApiClient($http, $tokens),
            $this->callback,
            $this->em,
            $this->logger,
        );

        // The registry by hand over the container's, so the only manager in it
        // is the one holding the MockHttpClient — the container's Graph manager
        // would answer with the real client and reach Microsoft.
        return new RegisterCalendarPushHandler($this->calendars, new CalendarPushRegistry([$manager]));
    }

    /** Google answers a watch with the channel it made, expiration in milliseconds. */
    private function watchResponse(string $resourceId, DateTimeImmutable $expiration): MockResponse
    {
        return new MockResponse(
            json_encode([
                'kind'       => 'api#channel',
                'resourceId' => $resourceId,
                'expiration' => (string) ($expiration->getTimestamp() * 1000),
            ], JSON_THROW_ON_ERROR),
            ['http_code' => 200, 'response_headers' => ['content-type' => 'application/json']],
        );
    }

    private function seed(): void
    {
        $this->user            = new User();
        $this->user->email     = 'register-push-' . uniqid('', true) . '@example.test';
        $this->user->nameFirst = 'Register';
        $this->user->nameLast  = 'Push';
        $this->user->roles     = ['ROLE_USER'];
        $this->user->password  = 'x';
        $this->em->persist($this->user);

        $this->account                = new Account();
        $this->account->usr           = $this->user;
        $this->account->email         = $this->user->email;
        $this->account->username      = $this->user->email;
        $this->account->authType      = AuthType::OAuth2->value;
        $this->account->oauthProvider = MailProvider::Google->value;
        $this->account->isActive      = true;
        $this->em->persist($this->account);

        $this->calendar           = new Calendar();
        $this->calendar->usr      = $this->user;
        $this->calendar->account  = $this->account;
        $this->calendar->name     = 'Work';
        $this->calendar->role     = CalendarRole::Remote;
        $this->calendar->remoteId = 'remote-cal-1';
        $this->em->persist($this->calendar);

        $this->em->flush();
    }
}
