<?php

declare(strict_types=1);

namespace App\Controller\Monitoring;

use App\Controller\ChecksCsrf;
use App\Entity\Monitoring\ClientError;
use App\Service\Monitoring\ClientErrorRecorder;
use JsonException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\RateLimiter\RateLimiterFactoryInterface;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Where the browser says something broke.
 *
 * Two doors, because two very different callers knock on them.
 *
 * ── /client-error ─────────────────────────────────────────────────────────
 * Our own script, reporting an uncaught error or a rejected promise. It holds a
 * session and the page it runs on has a CSRF token, so it sends one in
 * `X-CSRF-Token` like every other JSON POST in this application — and is
 * refused without it. That is not really about forgery: what a forged request
 * achieves here is a junk row in an admin panel. It is about the endpoint being
 * writable by anything on the internet that finds it, which the rate limiter
 * bounds and the token closes.
 *
 * ── /csp-report ───────────────────────────────────────────────────────────
 * The browser itself, reporting that the Content-Security-Policy stopped
 * something. This one CANNOT be protected the same way, and the difference is
 * not negotiable: the request is generated by the browser rather than by our
 * code, so it carries no header we chose, no token, and on a login page no
 * session either. It is public in security.yaml for that reason, with the rate
 * limiter as the only bound.
 *
 * That is worth having, because in production the full policy is ENFORCED
 * rather than report-only — so what arrives here is a list of things this
 * installation's policy actually blocked, in somebody's real browser, which is
 * not knowable any other way.
 *
 * ── Always 204, whatever happened ─────────────────────────────────────────
 * Including for a report that was thrown away, and including for one the
 * limiter refused. The caller is a browser that cannot act on an answer and
 * must not retry — and an endpoint that reported "kept" or "discarded" would be
 * an oracle telling anybody who asked which scripts this server thinks it sent.
 * See {@see ClientErrorRecorder} for what gets kept.
 */
final class ClientErrorController extends AbstractController
{
    use ChecksCsrf;

    /** Bigger than any honest report, small enough that nobody posts a file. */
    private const int MAX_BODY_BYTES = 16_384;

    public function __construct(
        private readonly ClientErrorRecorder         $recorder,
        private readonly RateLimiterFactoryInterface $clientErrorReportLimiter,
    ) {
    }

    #[Route('/client-error', name: 'app_client_error', methods: ['POST'])]
    public function report(Request $request): Response
    {
        $this->assertCsrf($request, 'ajax');

        if (false === $this->allowed($request)) {
            return new Response(status: Response::HTTP_NO_CONTENT);
        }

        $payload = $this->payload($request);

        if (null !== $payload) {
            $this->recorder->record(
                $payload,
                $request->getSchemeAndHttpHost(),
                $request->headers->get('User-Agent'),
            );
        }

        return new Response(status: Response::HTTP_NO_CONTENT);
    }

    /**
     * A CSP violation, in the shape the browser sends it.
     *
     * The body is `{"csp-report": {...}}` with hyphenated keys, which is the
     * report-uri format rather than anything this application chose. It is
     * flattened into the same shape as an error report here, so the recorder,
     * the table and the panel have one thing to understand instead of two.
     */
    #[Route('/csp-report', name: 'app_csp_report', methods: ['POST'])]
    public function csp(Request $request): Response
    {
        if (false === $this->allowed($request)) {
            return new Response(status: Response::HTTP_NO_CONTENT);
        }

        $payload = $this->payload($request);
        $report  = $payload['csp-report'] ?? null;

        if (false === is_array($report)) {
            return new Response(status: Response::HTTP_NO_CONTENT);
        }

        $this->recorder->record(
            [
                'kind' => ClientError::KIND_CSP,
                // The directive is the finding — "this page tried to load
                // something the policy does not allow" — and the blocked URI is
                // what it tried. Together they are the sentence somebody needs;
                // apart, neither is actionable.
                'message' => sprintf(
                    'Blocked by %s: %s',
                    self::str($report['violated-directive'] ?? $report['effective-directive'] ?? null) ?? 'the policy',
                    self::str($report['blocked-uri'] ?? null) ?? 'an unnamed resource',
                ),
                'source' => self::str($report['violated-directive'] ?? null),
                'line'   => $report['line-number'] ?? null,
                'column' => $report['column-number'] ?? null,
                'url'    => self::str($report['document-uri'] ?? null),
            ],
            $request->getSchemeAndHttpHost(),
            $request->headers->get('User-Agent'),
        );

        return new Response(status: Response::HTTP_NO_CONTENT);
    }

    private static function str(mixed $value): ?string
    {
        return is_string($value) && '' !== $value ? $value : null;
    }

    private function allowed(Request $request): bool
    {
        return $this->clientErrorReportLimiter->create($request->getClientIp())->consume()->isAccepted();
    }

    /**
     * The body as an array, or null for anything that is not one.
     *
     * Size-checked before it is decoded rather than after: the cheap refusal is
     * the point of the limit, and decoding sixteen megabytes to discover it was
     * sixteen megabytes is the thing being avoided.
     *
     * @return array<string, mixed>|null
     */
    private function payload(Request $request): ?array
    {
        $body = $request->getContent();

        if ('' === $body || self::MAX_BODY_BYTES < strlen($body)) {
            return null;
        }

        try {
            $decoded = json_decode($body, true, 8, JSON_THROW_ON_ERROR);
        } catch (JsonException) {
            return null;
        }

        return is_array($decoded) ? $decoded : null;
    }
}
