expose_php = 0
date.timezone = UTC
apc.enable_cli = 1
session.use_strict_mode = 1
zend.detect_unicode = 0

; https://symfony.com/doc/current/performance.html#configure-opcache-for-maximum-performance
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256

; https://symfony.com/doc/current/performance.html#don-t-check-php-files-timestamps
opcache.validate_timestamps = 0

; https://symfony.com/doc/current/performance.html#configure-the-php-realpath-cache
realpath_cache_size = 4096K
realpath_cache_ttl = 600

memory_limit = 2G
