; See https://github.com/docker-library/docs/tree/master/php#configuration
; https://symfony.com/doc/current/profiler.html#enabling-the-profiler-conditionally

; https://symfony.com/doc/current/performance.html#don-t-check-php-files-timestamps
opcache.validate_timestamps = 1

; https://xdebug.org/docs/all_settings#mode
xdebug.mode = ${XDEBUG_MODE}

; Open files in PhpStorm from the Xdebug stack / var_dump links
; xdebug.client_host = host.docker.internal
; xdebug.start_with_request = yes
